### ISSUE TITLE
Card is empty

### ISSUE THREAD

**Issue by fribse** [custom-cards/aftership-card#7] opened 2019-07-02 05:12 UTC
**Version of the cusom_component**
1.1.0

**Describe the bug**
After entering 3 parcels, the card is empty, and does not show any content (disappears)
Sensors shows:

State: 2
```
{
  "attribution": "Information provided by AfterShip",
  "delivered": 1,
  "intransit": 1,
  "pending": 1,
  "trackings": [
    {
      "name": "Sonoff Basic",
      "tracking_number": "67890",
      "slug": "postnl-international",
      "link": "https://track.aftership.com/postnl-international/67890",
      "last_update": "2019-07-01T15:14:11+00:00",
      "expected_delivery": null,
      "status": "Delivered",
      "last_checkpoint": {
        "slug": "danmark-post",
        "city": "Brøndby",
        "created_at": "2019-07-01T15:11:11+00:00",
        "location": "Brøndby, Brøndby, 2605, Danmark",
        "country_name": "Danmark",
        "message": "Forsendelsen er omdelt til modtagerens brevkasse",
        "country_iso3": "DNK",
        "tag": "Delivered",
        "subtag": "Delivered_001",
        "subtag_message": "Delivered",
        "checkpoint_time": "2019-07-01T15:29:49",
        "coordinates": [],
        "state": null,
        "zip": "2605"
      }
    },
    {
      "name": "23456",
      "tracking_number": "23456",
      "slug": "postnl-international",
      "link": "https://track.aftership.com/postnl-international/23456",
      "last_update": "2019-06-29T12:07:47+00:00",
      "expected_delivery": null,
      "status": "InTransit",
      "last_checkpoint": {
        "slug": "postnl-international",
        "city": null,
        "created_at": "2019-06-29T09:05:45+00:00",
        "location": null,
        "country_name": null,
        "message": "The item is on transport to the country of destination",
        "country_iso3": null,
        "tag": "InTransit",
        "subtag": "InTransit_007",
        "subtag_message": "Departure Scan",
        "checkpoint_time": "2019-06-28T14:37:00",
        "coordinates": [],
        "state": null,
        "zip": null
      }
    },
    {
      "name": "Havelys",
      "tracking_number": "12345",
      "slug": "postnl-international",
      "link": "https://track.aftership.com/postnl-international/12345",
      "last_update": "2019-06-29T09:05:08+00:00",
      "expected_delivery": null,
      "status": "Pending",
      "last_checkpoint": "Shipment pending"
    }
  ],
  "unit_of_measurement": "packages",
  "friendly_name": "aftership",
  "icon": "mdi:package-variant-closed"
}
```

**log**
javascript errors

Add your logs here.
TypeError: str is null
![console](https://user-images.githubusercontent.com/13660621/60484059-5b2abb80-9c98-11e9-802b-f47a29af2ed1.png)
![codelines](https://user-images.githubusercontent.com/13660621/60484061-6251c980-9c98-11e9-95e1-a329e5ee701a.png)

**Comment by thomasboegl1** [comment] 2019-07-04 09:08
Hey,

I got the same error today, the problem is that the sensor has a null last checkpoint location for the 23456 tracking number : 

```
 "last_checkpoint": {
        "slug": "postnl-international",
        "city": null,
        "created_at": "2019-06-29T09:05:45+00:00",
        "location": null,
```
Trying to find a solution, maybe just a `if != null` may work ?

**Comment by fribse** [comment] 2019-07-04 09:15
interesting

**Comment by MwC-Trexx** [comment] 2019-07-24 02:58
I am getting following javascript error.

`aftership-card.js:3122 Uncaught (in promise) TypeError: Cannot read property replace of undefined
    at HTMLElement._toTitleCase (aftership-card.js:3122)
    at aftership-card.js:3051
    at aftership-card.js:2486
    at NodePart.commit (aftership-card.js:636)
    at TemplateInstance.update (aftership-card.js:359)
    at NodePart._commitTemplateResult (aftership-card.js:706)
    at NodePart.commit (aftership-card.js:648)
    at render (aftership-card.js:1045)
    at Function.render$1 [as render] (aftership-card.js:1403)
    at HTMLElement.update (aftership-card.js:2349)`

**Sensor** shows the following:

`attribution: Information provided by AfterShip
pending: 1
delivered: 1
trackings: [object Object],[object Object]
unit_of_measurement: packages
friendly_name: aftership
icon: mdi:package-variant-closed`

**Aftership.Com shows**
1 Delivered : Fedex
1 Pending:  Amazon Ground

**Comment by jezzamine** [comment] 2019-08-16 10:12
My card won't show if i have any 'pending' shipments

**Comment by cjsmns** [comment] 2019-08-26 23:34
Also having this issue. Reported it on the forums about 2 weeks.

**Comment by iantrich** [comment] 2019-08-27 02:55
Fixed in https://github.com/custom-cards/aftership-card/releases/tag/1.1.1

**Closed as completed by iantrich** 2019-08-27 02:55 UTC
